name: Test dev env install script

on:
  pull_request:
    branches: [master]

jobs:
  test-dev-macos:
    runs-on: [self-hosted, macos]
    steps:
      - name: Test dev environment install on macOS
        run: "sudo /bin/bash -c \"$(curl -L -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/RomainFallet/symfony-dev-macos/${{ github.head_ref }}/macos10.15_configure_dev_env.sh)\""
